import jsPDF from "jspdf";

export interface ScanReportData {
  imageUrl?: string | null;
  cropType: string;
  diseaseName: string;
  diseaseNameMarathi: string;
  confidence: number;
  confidenceLevel?: string;
  severity: string;
  isHealthy?: boolean;
  needsExpert?: boolean;
  symptoms: string[];
  organicTreatment: string[];
  chemicalTreatment: string[];
  prevention: string[];
  possibleAlternatives?: string[];
  brands?: string[];
  fertilizerRecommendation: string;
  preventionTips: string;
  notes?: string;
  costEstimate?: number | null;
  costRange?: [number, number] | null;
  scanDate: string;
  location?: string;
  farmerName?: string;
  village?: string;
  rawModelOutput?: unknown;
}

// FasalMitra earthy theme (matches the site palette)
const THEME = {
  cream: [251, 248, 239] as const,
  green: [47, 107, 65] as const,
  greenSoft: [230, 240, 231] as const,
  soil: [122, 90, 60] as const,
  saffron: [232, 176, 75] as const,
  ink: [32, 42, 34] as const,
  muted: [110, 118, 108] as const,
};

/**
 * Pure-data PDF generation with jsPDF. No DOM screenshot, so CSS colors
 * (oklch etc.) are never parsed and the html2canvas oklch crash cannot happen.
 */
export async function generateScanReportPDF(data: ScanReportData): Promise<Blob> {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentW = pageWidth - margin * 2;
  let y = 0;

  const paintPage = () => {
    doc.setFillColor(...THEME.cream);
    doc.rect(0, 0, pageWidth, pageHeight, "F");
    doc.setFillColor(...THEME.green);
    doc.rect(0, 0, pageWidth, 78, "F");
    doc.setFillColor(...THEME.saffron);
    doc.rect(0, 78, pageWidth, 5, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(19);
    doc.text("FasalMitra", margin, 40);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text("Crop Health Report", margin, 60);
    // footer
    doc.setFillColor(...THEME.greenSoft);
    doc.rect(0, pageHeight - 34, pageWidth, 34, "F");
    doc.setFontSize(8);
    doc.setTextColor(...THEME.muted);
    doc.text("Generated by FasalMitra · AI advisory, not a substitute for a Krishi officer", margin, pageHeight - 14);
    doc.setTextColor(...THEME.ink);
  };

  const newPage = () => { doc.addPage(); paintPage(); y = 105; };
  const ensure = (need: number) => { if (y + need > pageHeight - 55) newPage(); };

  paintPage();
  y = 105;

  if (data.imageUrl) {
    try {
      const imgData = await fetchImageAsBase64(data.imageUrl);
      doc.setDrawColor(...THEME.green);
      doc.setLineWidth(1);
      doc.roundedRect(margin - 4, y - 4, 208, 158, 6, 6, "S");
      doc.addImage(imgData, "JPEG", margin, y, 200, 150);
      y += 170;
    } catch {
      doc.setTextColor(...THEME.muted);
      doc.setFontSize(10);
      doc.text("(Photo could not be embedded)", margin, y);
      doc.setTextColor(...THEME.ink);
      y += 20;
    }
  }

  const heading = (label: string) => {
    ensure(46);
    doc.setFillColor(...THEME.greenSoft);
    doc.roundedRect(margin, y - 12, contentW, 22, 5, 5, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...THEME.green);
    doc.text(label.toUpperCase(), margin + 8, y + 3);
    doc.setTextColor(...THEME.ink);
    y += 24;
  };

  const para = (value: string) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(value || "-", contentW);
    for (const line of lines as string[]) {
      ensure(16);
      doc.text(line, margin, y);
      y += 13;
    }
    y += 8;
  };

  const bullets = (items: string[]) => {
    const list = (items ?? []).filter((x) => x && String(x).trim());
    if (list.length === 0) { para("-"); return; }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    for (const item of list) {
      const lines = doc.splitTextToSize(String(item), contentW - 16) as string[];
      lines.forEach((line, i) => {
        ensure(16);
        if (i === 0) {
          doc.setFillColor(...THEME.saffron);
          doc.circle(margin + 4, y - 3, 2.2, "F");
        }
        doc.text(line, margin + 16, y);
        y += 13;
      });
    }
    y += 8;
  };

  const kv = (rows: Array<[string, string]>) => {
    doc.setFontSize(10);
    for (const [k, v] of rows) {
      ensure(18);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...THEME.soil);
      doc.text(k, margin, y);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...THEME.ink);
      const lines = doc.splitTextToSize(v || "-", contentW - 150) as string[];
      doc.text(lines, margin + 150, y);
      y += Math.max(14, lines.length * 13);
    }
    y += 8;
  };

  const v = (s?: string | null) => (s && String(s).trim() ? String(s) : "-");

  heading("Report details");
  kv([
    ["Scan date", v(data.scanDate)],
    ["Scan location", v(data.location) === "-" ? "Location not available" : v(data.location)],
    ["Farmer", v(data.farmerName)],
    ["Village", v(data.village)],
    ["Crop", v(data.cropType)],
  ]);

  heading("Diagnosis");
  kv([
    ["Disease (EN)", v(data.diseaseName)],
    ["Disease (MR)", v(data.diseaseNameMarathi)],
    ["Plant status", data.isHealthy ? "Healthy" : "Issue detected"],
    ["Confidence", `${Number.isFinite(data.confidence) ? data.confidence : 0}%${data.confidenceLevel ? ` (${data.confidenceLevel})` : ""}`],
    ["Severity", v(data.severity)],
    ["Expert review needed", data.needsExpert ? "Yes" : "No"],
  ]);

  heading("Symptoms observed");
  bullets(data.symptoms);

  heading("Organic treatment");
  bullets(data.organicTreatment);

  heading("Chemical treatment");
  bullets(data.chemicalTreatment);
  if (data.brands?.length) para(`Available brands: ${data.brands.join(", ")}`);

  heading("Prevention");
  bullets(data.prevention);
  if (data.preventionTips) para(data.preventionTips);

  if (data.possibleAlternatives?.length) {
    heading("Other possible causes");
    bullets(data.possibleAlternatives);
  }

  heading("Inputs & cost");
  kv([
    ["Fertilizer advice", v(data.fertilizerRecommendation)],
    ["Estimated cost", data.costEstimate ? `Rs ${data.costEstimate} / acre` : "-"],
    ["Typical cost range", data.costRange ? `Rs ${data.costRange[0]} - Rs ${data.costRange[1]} / acre` : "-"],
  ]);

  if (data.notes) {
    heading("Notes");
    para(data.notes);
  }

  if (data.rawModelOutput) {
    heading("Full model output (raw)");
    doc.setFont("courier", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...THEME.muted);
    const raw = JSON.stringify(data.rawModelOutput, null, 2);
    const lines = doc.splitTextToSize(raw, contentW) as string[];
    for (const line of lines) {
      ensure(12);
      doc.text(line, margin, y);
      y += 10;
    }
    doc.setTextColor(...THEME.ink);
  }

  const safeDate = (data.scanDate || new Date().toISOString().slice(0, 10)).replace(/[^\dA-Za-z-]/g, "-");
  doc.save(`FasalMitra_Report_${safeDate}.pdf`);
  return doc.output("blob");
}

async function fetchImageAsBase64(url: string): Promise<string> {
  if (url.startsWith("data:")) return url;
  const res = await fetch(url);
  const blob = await res.blob();
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}
