import jsPDF from "jspdf";

export interface ScanReportData {
  imageUrl?: string | null;
  cropType: string;
  diseaseName: string;
  diseaseNameMarathi: string;
  confidence: number;
  severity: string;
  symptoms: string[];
  organicTreatment: string;
  chemicalTreatment: string;
  fertilizerRecommendation: string;
  preventionTips: string;
  scanDate: string;
  farmerName?: string;
  village?: string;
}

/**
 * Pure-data PDF generation with jsPDF. No DOM screenshot, so CSS colors
 * (oklch etc.) are never parsed and the html2canvas oklch crash cannot happen.
 */
export async function generateScanReportPDF(data: ScanReportData): Promise<Blob> {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;
  let y = 50;

  doc.setFillColor(21, 128, 61);
  doc.rect(0, 0, pageWidth, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("FasalMitra - Crop Health Report", margin, 45);
  y = 100;

  if (data.imageUrl) {
    try {
      const imgData = await fetchImageAsBase64(data.imageUrl);
      doc.addImage(imgData, "JPEG", margin, y, 200, 150);
      y += 165;
    } catch {
      doc.setTextColor(150, 150, 150);
      doc.setFontSize(10);
      doc.text("(Photo could not be embedded)", margin, y);
      y += 20;
    }
  }

  doc.setTextColor(0, 0, 0);

  const addSection = (label: string, value: string) => {
    if (y > 750) { doc.addPage(); y = 50; }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(label, margin, y);
    y += 16;
    if (value) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      const lines = doc.splitTextToSize(value || "-", pageWidth - margin * 2);
      doc.text(lines, margin, y);
      y += lines.length * 13 + 12;
    } else {
      y += 6;
    }
  };

  const v = (s?: string | null) => (s && String(s).trim() ? String(s) : "-");

  addSection("Scan Date:", v(data.scanDate));
  if (data.farmerName || data.village) {
    addSection("Farmer / Village:", `${v(data.farmerName)} / ${v(data.village)}`);
  }
  addSection("Crop Type:", v(data.cropType));
  addSection(`Diagnosis: ${data.diseaseName || "-"}`, v(data.diseaseNameMarathi));
  addSection("Confidence:", `${Number.isFinite(data.confidence) ? data.confidence : 0}%`);
  addSection("Severity:", v(data.severity));
  addSection("Symptoms Observed:", v((data.symptoms ?? []).join(", ")));
  addSection("Organic Treatment:", v(data.organicTreatment));
  addSection("Chemical Treatment:", v(data.chemicalTreatment));
  addSection("Fertilizer Recommendation:", v(data.fertilizerRecommendation));
  addSection("Prevention Tips:", v(data.preventionTips));

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by FasalMitra", margin, 820);

  const safeDate = (data.scanDate || new Date().toISOString().slice(0, 10)).replace(/[^\dA-Za-z-]/g, "-");
  doc.save(`FasalMitra_Report_${safeDate}.pdf`);
  return doc.output("blob");
}

async function fetchImageAsBase64(url: string): Promise<string> {
  if (url.startsWith("data:")) return url;
  const res = await fetch(url);
  const blob = await res.blob();
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}
